### ISSUE TITLE
Examples and tests do not run

### ISSUE THREAD

**Issue by niceyeti** [HIPS/autograd#525] opened 2019-07-13 22:03 UTC
This looks like a simple import error w.r.t logsumexp. I installed autograd-1.2 with pip3 and could not run rnn.py or several other examples. Built/installed from source repo, identical result.

Repro:
>   cd ./autograd/tests
>   python3 test_scipy.py 

Result:
> Traceback (most recent call last):
>   File "test_scipy.py", line 14, in <module>
>     import autograd.scipy.signal
>   File "/home/[user]/.local/lib/python3.5/site-packages/autograd/scipy/__init__.py", line 7, in <module>
>     from . import misc
>   File "/home/[user]/.local/lib/python3.5/site-packages/autograd/scipy/misc.py", line 7, in <module>
>     logsumexp = primitive(scipy.misc.logsumexp)
> AttributeError: module 'scipy.misc' has no attribute 'logsumexp'

**Comment by slinderman** [comment] 2019-07-15 00:39
This is a duplicate of https://github.com/HIPS/autograd/issues/501.

The master branch should be fixed but the change hasn't made it to PyPI yet.

**Closed** 2019-07-15 00:40 UTC
