### ISSUE TITLE
Traceback not displayed if backward pass errors in reverse mode

### ISSUE THREAD

**Issue by agriyakhetarpal** [HIPS/autograd#660] opened 2024-12-02 13:40 UTC
> This might be from an error occurring during the backward pass of reverse-mode autodiff. When an error occurs during the backward pass you can't get a traceback to the corresponding point in user code. It might be something else though - feel free to paste an example if you hit this again and I can look into it.

_Originally posted by @j-towns in https://github.com/HIPS/autograd/issues/643#issuecomment-2510845561_

**Comment by agriyakhetarpal** [comment] 2024-12-02 13:45
One example is this code, now fixed in #643:

```python
from autograd.test_util import combo_check
from autograd import numpy as np
import autograd.numpy.random as NPR

R = npr.randn

def test_logsumexp1():
        combo_check(special.logsumexp, [0], modes=["fwd", "rev"])(
            [1.1], R(4), R(3, 4)], axis=[None, 0], keepdims=[True, False]
        )
```

The forward mode check will pass here, but the reverse mode fails when using nightly wheels of SciPy (which can be installed with `pip install scipy -i "https://anaconda.org/scientific-python-nightly-wheels/simple"`). Please let me know in case there are troubles with this and I can try to produce a better reproducer.

**Comment by j-towns** [comment] 2024-12-02 14:19
I think this is a duplicate of https://github.com/HIPS/autograd/issues/359 (I should have linked to that before).

**Closed by j-towns** 2024-12-02 14:19 UTC

**Comment by agriyakhetarpal** [comment] 2024-12-02 15:36
No worries, and thanks! It would be great if you could take a look at it sometime. I could do so too, but we can't deny that you have the upper ground, given that you have more experience in this area. :)
