### ISSUE TITLE
Numpy wrapper does not convert None to NaN like real numpy does.

### ISSUE THREAD

**Issue by christian-oudard** [HIPS/autograd#467] opened 2019-01-24 20:50 UTC
autograd_bug.py:
```
import numpy as np
print(np.array([1, None], dtype=np.float))
from autograd import numpy as np
print(np.array([1, None], dtype=np.float))
```
output:
```                                                                              
$ python autograd_bug.py
[ 1. nan]
Traceback (most recent call last):
  File "autograd_bug.py", line 4, in <module>
    print(np.array([1, None], dtype=np.float))
  File "/home/christian/.local/lib/python3.6/site-packages/autograd/numpy/numpy_wrapper.py", line 60, in array
    return array_from_args(args, kwargs, *map(array, A))
  File "/home/christian/.local/lib/python3.6/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/home/christian/.local/lib/python3.6/site-packages/autograd/numpy/numpy_wrapper.py", line 79, in array_from_args
    return _np.array(args, *array_args, **array_kwargs)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by agriyakhetarpal** [comment] 2024-08-25 23:30
Hi @christian-oudard, in recent versions of NumPy, we now need to specify `np.float64` (or `np.float32`) as the array's dtype. However, I can't reproduce the error, neither with NumPy version 1.26.4 nor NumPy version 2.1.0 with the code snippet you added – I suspect that this might have been resolved with some NumPy/Autograd version at some point in time.

Thanks for taking the time to open an issue, however! We can close this, please feel free to reach out in case there are any more bugs.

**Closed by agriyakhetarpal** 2024-08-25 23:30 UTC
