### ISSUE TITLE
norm fails at 0

### ISSUE THREAD

**Issue by keithbriggs** [HIPS/autograd#268] opened 2017-08-03 12:08 UTC
import autograd.numpy as np
from autograd import value_and_grad
def f(x): return np.linalg.norm(x)
x=np.zeros((1,))
f_with_grad=value_and_grad(f)
print(f_with_grad(x))

/usr/local/lib/python3.4/dist-packages/autograd-1.1.10-py3.4.egg/autograd/core.py:82: RuntimeWarning: divide by zero encountered in true_divide
  result_value = self.fun(*argvals, **kwargs)
/usr/local/lib/python3.4/dist-packages/autograd-1.1.10-py3.4.egg/autograd/core.py:82: RuntimeWarning: invalid value encountered in multiply
  result_value = self.fun(*argvals, **kwargs)
(0.0, array([ nan]))

**Comment by j-towns** [comment] 2017-08-03 12:17
Hi there, I believe this is a duplicate of https://github.com/HIPS/autograd/issues/151. As I pointed out there, norms aren't in general differentiable at zero, so it's debatable whether this is a bug.

**Comment by keithbriggs** [comment] 2017-08-03 12:19
Ok, fair enough.


K


________________________________

**Closed** 2017-08-22 16:59 UTC
