### ISSUE TITLE
Jacobian within Jacobian not compatible with np.dot()

### ISSUE THREAD

**Issue by timbailey74** [HIPS/autograd#107] opened 2016-05-24 04:16 UTC
Dear autograd guys,

First, thank you for your excellent library; I am finding it really useful. Below is an issue that I believe exists with the implementation of jacobian(). 

Context: I am computing a Jacobian matrix inside a function for which I am calculating a Jacobian. That is, a Jacobian within a Jacobian. Note: this is *not* a Hessian calculation.

Issue: The format of the inner Jacobian matrix does not appear to be compatible with that of other vectors in the function when using np.dot().

Suspected reason: I think that the current format of the Jacobian matrix is not correct. A revised format is suggested.

Below is the code where this issue arises. Sorry that it includes a lot of extraneous detail, but hopefully the essence is not too difficult to see. That is, that the formats of internal Jacobian matrix H and vector xnext are incompatible for np.dot(H, xnext).

Thanks for your time, and sorry if I have done something stupid....

Tim.

--------------------------------------

Removed code from here, added as attachment below

**Comment by timbailey74** [comment] 2016-05-24 04:22
Sorry, the formatting of the code above came out badly. Will try an attachment here.
[autograd issue.txt](https://github.com/HIPS/autograd/files/278744/autograd.issue.txt)

**Comment by mattjj** [comment] 2016-05-24 11:28
Glad you like autograd!

Can you give us a minimal example that reproduces the error, or tell us what the error is and provide a traceback?

Usually when you see an ndarray of dtype object with a bunch of autograd-boxed FloatNodes inside it means that some unwrapped numpy function was called on an autograd ArrayNode. Is it possible that your code is calling numpy functions (rather than autograd.numpy functions) somewhere?

**Comment by mattjj** [comment] 2016-05-24 11:30
For easier reference, I'm pasting the contents of your code attachment here:

```python
import autograd.numpy as np
from autograd import grad, jacobian

def test_jacobian_calculation():
    t, dt = 1., 0.01
    x = np.array([0.1, 0.1, 0.1])
    jac = jacobian(crank_nicolson_step, 2)
    J1 = jac(lorenz, t, x, dt, ())  # lorenz(t, x) is a differential equation model

# Broken; it appears that the format of H is incompatible with that of xnext	
def crank_nicolson_step(model, t, x, dt, args, w=0.5):
    xnext = initial_guess(model, t, x, dt, args)  # simple function, no numpy operations
    jacmodel = jacobian(crank_nicolson_step_twosided, 3)  # another simple function
    for _ in range(2):  # improve xnext, by iterative least-squares refinement
        zs = crank_nicolson_step_twosided(model, t, x, xnext, dt, args, w)
        H = jacmodel(model, t, x, xnext, dt, args, w)  
        v = np.dot(H, xnext) - zs  # Code breaks here; cannot perform dot-product!!
        y = np.dot(H.T, v)
        Y = np.dot(H.T, H)
        xnext = np.linalg.solve(Y, y)
    return xnext
```

Here is the format of H:	

```
>>> H
Out[1]: 
array([[<autograd.core.FloatNode object at 0x0000000004727BE0>,
       <autograd.core.FloatNode object at 0x0000000004727AC8>,
       <autograd.core.FloatNode object at 0x0000000004727B70>],
      [<autograd.core.FloatNode object at 0x0000000004727B00>,
       <autograd.core.FloatNode object at 0x0000000004727BA8>,
       <autograd.core.FloatNode object at 0x0000000004727C18>],
      [<autograd.core.FloatNode object at 0x0000000004727CC0>,
       <autograd.core.FloatNode object at 0x0000000004727C50>,
       <autograd.core.FloatNode object at 0x0000000004727A90>]], dtype=object)
```

Here is the format of xnext:

```
>>> xnext
Out[1]: <autograd.numpy.numpy_extra.ArrayNode at 0x471eac8>
>>> xnext[0]
Out[2]: <autograd.core.FloatNode at 0x5a2fe10>
```

The problem is resolved if, instead of jacobian(), we use grad() and loop over the rows of the Jacobian matrix to compose H.

```
def crank_nicolson_step(model, t, x, dt, args, w=0.5):
    def crank_nicolson_step_i(i, *args):  # returns i-th scalar element 
        return crank_nicolson_step_twosided(*args)[i]
    xnext = initial_guess(model, t, x, dt, args)  
    gradmodel = grad(crank_nicolson_step_i, 4)
    for _ in range(2):  
        zs = crank_nicolson_step_twosided(model, t, x, xnext, dt, args, w)
        H = np.array([gradmodel(i, model, t, x, xnext, dt, args, w) for i in range(len(x))])  # loop over scalar function to compose H
        v = np.dot(H, xnext) - zs
        y = np.dot(H.T, v)
        Y = np.dot(H.T, H)
        xnext = np.linalg.solve(Y, y)
    return xnext	
```

Here is the format of H that is compatible with xnext:

```
>>> H
Out[1]: <autograd.numpy.numpy_extra.ArrayNode at 0x575a3c8>
>>> H[0]
Out[2]: <autograd.numpy.numpy_extra.ArrayNode at 0x5ad7eb8>
>>> H[0,0]
Out[3]: <autograd.core.FloatNode at 0x5ad76d8>
```

**Comment by timbailey74** [comment] 2016-05-24 13:17
Attached is a (semi-)working version of the code insofar as it runs and then fails at the stated point.

[test_autograd_jacobian_issue.txt](https://github.com/HIPS/autograd/files/279577/test_autograd_jacobian_issue.txt)

**Comment by timbailey74** [comment] 2016-05-24 13:19
Here is the traceback:

Traceback (most recent call last):
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\numpy\numpy_extra.py", line 85, in new_array_node
    return array_dtype_mappings[value.dtype](value, tapes)
KeyError: dtype('O')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 62, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 42, in list_fun
    val = fun(*args, **kwargs)
  File "C:/Users/tbailey/Documents/GitHub/iterated-linearised-smoothing/iterated_linearised_smoothing/sandbox/test_autograd_jacobian_issue.py", line 32, in crank_nicolson_step_broken
    v = np.dot(H, xnext) - zs  # Code breaks here; cannot perform dot-product!!
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 167, in __call__
    result = new_node(result, tapes)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 188, in new_node
    return Node.type_mappings[type(value)](value, tapes)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\numpy\numpy_extra.py", line 87, in new_array_node
    raise TypeError("Can't differentiate wrt numpy arrays of dtype {0}".format(value.dtype))
TypeError: Can't differentiate wrt numpy arrays of dtype object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tbailey/Documents/GitHub/iterated-linearised-smoothing/iterated_linearised_smoothing/sandbox/test_autograd_jacobian_issue.py", line 72, in <module>
    test_jacobian_calculation()
  File "C:/Users/tbailey/Documents/GitHub/iterated-linearised-smoothing/iterated_linearised_smoothing/sandbox/test_autograd_jacobian_issue.py", line 65, in test_jacobian_calculation
    J = jac(lorenz, t, x, dt, ())
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 50, in jacfun
    start_node, end_nodes, tape = forward_pass(list_fun, args, kwargs, argnum)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 63, in forward_pass
    except Exception as e: add_extra_error_message(e)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 392, in add_extra_error_message
    raise_(etype, value, traceback)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\future\utils\__init__.py", line 414, in raise_
    raise exc.with_traceback(tb)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 62, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 42, in list_fun
    val = fun(*args, **kwargs)
  File "C:/Users/tbailey/Documents/GitHub/iterated-linearised-smoothing/iterated_linearised_smoothing/sandbox/test_autograd_jacobian_issue.py", line 32, in crank_nicolson_step_broken
    v = np.dot(H, xnext) - zs  # Code breaks here; cannot perform dot-product!!
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 167, in __call__
    result = new_node(result, tapes)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\core.py", line 188, in new_node
    return Node.type_mappings[type(value)](value, tapes)
  File "C:\Users\tbailey\AppData\Local\Continuum\Anaconda3\lib\site-packages\autograd\numpy\numpy_extra.py", line 87, in new_array_node
    raise TypeError("Can't differentiate wrt numpy arrays of dtype {0}".format(value.dtype))
TypeError: Can't differentiate wrt numpy arrays of dtype object

**Comment by mattjj** [comment] 2016-05-24 13:49
I can run that code without error. I think you might be experiencing a bug from an old version of autograd.

Can you try upgrading autograd? I think the pip version has a fix for this bug, though you can always get the github version for the latest stuff.

**Comment by mattjj** [comment] 2016-05-24 13:52
I just verified that the current pip version indeed has the jacobian fix in it. It looks like we fixed it in 1.1.4.

**Comment by timbailey74** [comment] 2016-05-24 14:05
Yep. Works for me now. Thanks a lot.

Tim.

**Closed** 2016-05-24 14:53 UTC

**Comment by mattjj** [comment] 2016-05-24 15:13
Great, glad that helped!
