### ISSUE TITLE
issues with arange

### ISSUE THREAD

**Issue by MInner** [HIPS/autograd#229] opened 2017-05-24 23:20 UTC
For testing purposes I tried passing `np.arange`-ed data through the gradients and stumbled upon this weird issue:

```
import autograd
import autograd.numpy as np
import numpy as _np

f = lambda x: np.sum(x)
g = autograd.grad(f)
print(g(np.ones(4))) # okay
print(g(_np.ones(4))) # okay
print(g(np.array([1, 1, 1, 1])))  # error
print(g(_np.array([1, 1, 1, 1]))) # error
print(g(np.arange(4))) # error
```

**upd**: got it, for others who might stuble upon it - the issue is in the fact that [1, 1, 1, 1] are *int*'s, not *float*'s

**Comment by mattjj** [comment] 2017-05-25 01:38
If you do `np.arange(4.)` it will produce floats, which might come in handy! I'm going to close this issue as intended behavior.

**Closed by mattjj** 2017-05-25 01:38 UTC
